### PR TITLE
changes from v1.0.1 to windy branch

### PR DESCRIPTION
**Pull request by RoguedBear**
enjoy the merge conflicts

### CODE REVIEW

**Comment by Ya-s-h** [comment]
> enjoy the merge conflicts

**Comment by RoguedBear** [comment]
whoops. did a whoopsie branch swithceroonie

**Comment by RoguedBear** [comment]
wait no. Pull request is right. confused me didn't you @Ya-s-h

**Comment by RoguedBear** [comment]
nvm

**Pull request closed without merging**
